### ISSUE TITLE
update Home with good UI

### ISSUE THREAD

**Issue by adhavalboy** [darthgera123/QuizApp#14]
![image](https://user-images.githubusercontent.com/16662228/53296346-93764500-3833-11e9-8ce4-2db87fa0d8f8.png)
current view of Home improve it and add some images in home

**Comment by InfiniteVerma** [comment]
I will like to work on this issue. Gssoc participant.

**Comment by adhavalboy** [comment]
Thanks for showing your interest.

**Comment by Jayashree-panda** [comment]
hello @adhavalboy . I would like to improve the UI of homepage. Can I?
