### ISSUE TITLE
Convert menubar to dropdown list for small screens

### ISSUE THREAD

**Issue by h-sinha** [darthgera123/QuizApp#20]

**Comment by Jayashree-panda** [comment]
@h-sinha can I do it?

**Comment by h-sinha** [comment]
Sure, go ahead

**Comment by parammittal16** [comment]
@h-sinha interested to do this one may I proceed ?

**Comment by h-sinha** [comment]
@parammittal16 , @Jayashree-panda is already working on it. You can take up some other issue.

**Comment by shahkv95** [comment]
Heyy @h-sinha, I would like contribute for the same.

**Comment by adhavalboy** [comment]
@shahkv95  yes, you can start working on it.

**Comment by Rohithgilla12** [comment]
Hey @Jayashree-panda , any update on the progress?
