### ISSUE TITLE
add how to play section

### ISSUE THREAD

**Issue by adhavalboy** [darthgera123/QuizApp#22]
Add one more section of how to play quiz and it should contain from sign up to and of quiz how to play and how to create etc.

**Comment by kuja24** [comment]
This is a frontend only part , is it so ? If yes then I would like to work on this?

**Comment by adhavalboy** [comment]
@kuja24 yes

**Comment by kuja24** [comment]
What content has to be written. Can you help me through this ?

**Comment by kuja24** [comment]
The command npm install ran without any errors. But npm start does not work fine. please help.
And I also want to know the content that has to be written in the how to play section

![doubt](https://user-images.githubusercontent.com/36929301/54712103-7c482000-4b71-11e9-98ba-81538ab09a30.png)

**Comment by adhavalboy** [comment]
@kuja24 you forgot to change folder to react-app
cd react-app
npm install
npm start

**Comment by kuja24** [comment]
Sir , please tell me what has to be written in how to play section?

**Comment by kuja24** [comment]
And right now I can only view the part to signup and login. Do I need to install the back-end(Go) to be able to signup & login? Because right now I signed up but nothing happened

**Comment by adhavalboy** [comment]
@kuja24 config back-end first

**Comment by kuja24** [comment]
Okay , will do it now. But till then can you tell me the content

**Comment by adhavalboy** [comment]
@kuja24 In how to play section you need to write guidelines for playing kind of help section or frequently ask question type. How to create a quiz ? how to show leader board etc.

**Comment by kuja24** [comment]
And it has to be added in the main section along with signup and login?

**Comment by adhavalboy** [comment]
@kuja24 yes

**Comment by kuja24** [comment]
ERROR:
package github.com/gin-contrib/cors: cannot download, C:\Users\HP 15\go is a GOROOT, not a GOPATH. For more details see:
'go help gopath'
The following are the details of the goroot and go path. Please tell me the commands to be used
![image](https://user-images.githubusercontent.com/36929301/55006536-e9d9cd80-5003-11e9-8324-116ef90b468e.png)

**Comment by kuja24** [comment]
To set your GOPATH add these lines into ~/.bashrc
    export GOPATH=$HOME/go
    export PATH=$PATH:$GOROOT/bin:$GOPATH/bin

I tried the windows equivalent of these commands but i still get the same error

**Comment by adhavalboy** [comment]
@kuja24 please create it as new issue if you get any error :)

**Comment by kuja24** [comment]
But i think it is in my system only due to some system installation.Still should i create an issue?

**Comment by adhavalboy** [comment]
@kuja24  yes because if another person got the same error then it would be easy to solve. create new issue I will assign someone to solve it.

**Comment by kuja24** [comment]
Done Sir!

**Comment by kuja24** [comment]
@adhavalboy 
![image](https://user-images.githubusercontent.com/36929301/55026351-d1c87500-5028-11e9-93e8-0216520b353b.png)

**Comment by kuja24** [comment]
@adhavalboy @h-sinha @darthgera123 please help!!

**Comment by darthgera123** [comment]
have you done git add and git commit?

**Comment by kuja24** [comment]
No but I am trying to set up Go environment.Still Do i need to do that ?
