### ISSUE TITLE
Setting Gopath for installing Go on windows

### ISSUE THREAD

**Issue by kuja24** [darthgera123/QuizApp#28]
These are the details of the go environment.
![image](https://user-images.githubusercontent.com/36929301/55008044-6ec5e680-5006-11e9-9761-6a16abee3b6a.png)
To set your GOPATH add these lines into ~/.bashrc
export GOPATH=$HOME/go
export PATH=$PATH:$GOROOT/bin:$GOPATH/bin

I tried the windows equivalent of these commands but i still get the same error
Please tell the appropriate commands

**Comment by sahilit** [comment]
Try this https://github.com/golang/go/wiki/SettingGOPATH#windows
