### ISSUE TITLE
Sort on Button

### ISSUE THREAD

**Issue by darthgera123** [darthgera123/QuizApp#3]
Currently, when you are in the leaderboard section, the sorting of scores takes place only when you press the button. However, this should be automatic.

**Comment by sahilit** [comment]
On pressing the button the sorting is not working. 
I am interested in fixing this bug under Gssoc 2019. Can I?

**Comment by darthgera123** [comment]
well ideally we dont want the button as it should be sorted automatically. See of you want to fix that
