### ISSUE TITLE
Redirect

### ISSUE THREAD

**Issue by darthgera123** [darthgera123/QuizApp#7]
On Logging out, the site doesn't redirect to the home page and instead redirects to a blank page

**Comment by tyagipr** [comment]
can i work on this issue under GSSoC2019?@darthgera123

**Comment by darthgera123** [comment]
yes

**Comment by tyagipr** [comment]
kindly add me as assignees for the following issue

**Comment by darthgera123** [comment]
whats the status

**Comment by sahilit** [comment]
Hey @tyagipr If you are not free can I work on it?

**Comment by sahilit** [comment]
Hey I have solved the bug

**Comment by sahilit** [comment]
On Logging out the site is redirecting to the Home Page now.
So is this issue fixed or need more changes?
